domains: add domain mittelweser
freifunkh/site pull request #38
Opened 2019-06-19 22:05 UTC by Dark4MD

Aiyion suggested to make it a pull request to check my changes i intended to do for adding the domain Mittelweser-Region which includes Nienburg and some other cities that are located along the Weser.

2019-06-21 16:33 UTC, AiyionPrime requested changes

2019-06-21 16:33 UTC, AiyionPrime commented on domains/dom15.conf
> +		mittelweser = 'Mittelweser-Region'
lass doch auch deine Zeile mit einem Komma enden, wie die anderen auch

2019-06-21 16:33 UTC, AiyionPrime commented on domains/gen.py
> +    15: { "names": { "wunstorf": "Wunstorf", "neustadt": "Neustadt", "mittelweser": "Mittelweser-Region" } },
"Mittelweser-Region" ist ganz schön groß?
https://www.mittelweser-tourismus.de/
Wir sollten aufpassen, das wir da nicht Nordheide nerven.

2019-06-21 22:20 UTC, Dark4MD commented on domains/gen.py
> +    15: { "names": { "wunstorf": "Wunstorf", "neustadt": "Neustadt", "mittelweser": "Mittelweser-Region" } },
Hast recht ist der Karte nach echt sehr groß, ich werde das auf "Landkreis Nienburg/Weser" ändern, dass passt dann doch besser.

2019-06-21 22:21 UTC, Dark4MD commented on domains/dom15.conf
> +		mittelweser = 'Mittelweser-Region'
das muss mir untergegangen sein, ich hatte eigentlich extra geguckt wie es vorher war und anscheinend dann doch vergessen so zu machen. wird auch korrigiert

2019-06-24 13:36 UTC, AiyionPrime commented
@Dark4MD hör mal auf force push zu nutzen. Das Konzept von einem VCS wie git ist nicht, dass die history sauber aussieht, sondern, dass es eine Historie darüber gibt, was wirklich passiert ist.

Es ist überdurchschnittlich nervig für alle beteiligten zu prüfen, ob die History durch deinen Beitrag kaputt geht und man deshalb jetzt auf allen remotes force nutzen muss.

2019-06-24 14:06 UTC, Dark4MD commented
@AiyionPrime ok werd ich in Zukunft unterlassen. War mir bisher nicht bewusst das es so weitreichende folgen haben kann.

2019-06-27 20:28 UTC, AiyionPrime requested changes
Das hier wäre der einzige Eintrag mit LK.

2019-06-27 20:28 UTC, AiyionPrime commented on domains/dom15.conf
> +		nienburg = 'Landkreis Nienburg/Weser',
Lass mal das Landkreis weg, dann ist es einheitlicher.

2019-06-27 20:28 UTC, AiyionPrime commented on domains/gen.py
> +    15: { "names": { "wunstorf": "Wunstorf", "neustadt": "Neustadt", "nienburg": "Landkreis Nienburg/Weser" } },
Hier halt auch.

2019-06-27 20:38 UTC, moridius requested changes
Okay wenn "Landkreis" entfernt wird.

2019-06-28 22:16 UTC, Dark4MD commented on domains/dom15.conf
> +		nienburg = 'Landkreis Nienburg/Weser',
erledigt

2019-06-28 22:16 UTC, Dark4MD commented on domains/gen.py
> +    15: { "names": { "wunstorf": "Wunstorf", "neustadt": "Neustadt", "nienburg": "Landkreis Nienburg/Weser" } },
ebenfalls

2019-07-03 07:06 UTC, AiyionPrime approved these changes

2019-07-03 13:59 UTC, merged