fixed 841 patch, mac address setting changed
freifunkh/site pull request #78
Opened 2022-11-06 18:24 UTC by Dark4MD

The WAN MAC Address on the WAN interface changes on every reboot
The setting of the MAC Address is slightly changed in openwrt 22.03.
Must have happend at [https://github.com/openwrt/openwrt/commit/abc17bf306acd1c5954fbba97134e891439f917c](url)

This PR is untested for now but a test build is running.

2023-02-02 09:59 UTC, Dark4MD commented
On a 841v11 this fixes the MAC Address change, it now stays the same (pulled from uboot like before).

2023-02-02 14:00 UTC, AiyionPrime requested changes
Other than the commit-message revert this looks fine.

2023-02-02 14:00 UTC, AiyionPrime commented on patches/0003-patches-openwrt-add-TL-WR841ND-N-8M-and-16M-variants.patch
> ++++ b/patches/openwrt/0010-add-TL-WR841ND-N-8M-and-16M-Variants.patch
I liked the lowercase commit message more; any reason to revert that?
Secondly the new patchnumber should become 0011.

```suggestion
+++ b/patches/openwrt/0011-add-TL-WR841ND-N-8M-and-16M-variants-to-ath79.patch
```

2023-04-25 23:20 UTC, AiyionPrime commented
Addressing this will become better documented till Thursday.
I want this in our test for vH36 and vH37, but this needs some changes.
Currently calling `make refresh-patches` leaves uncommited changes in the gluon repo, when this patch has been applied. That would be a good first step to explore :)

Another good one would be to address the remarks from above and using the old patch as base for your intended changes instead of the commit before that, which reintroduces the old Uppercase Patchname agein :)

2023-05-04 20:20 UTC, AiyionPrime approved these changes

2023-05-04 20:47 UTC, s-2 approved these changes
Looks good for OpenWrt v22.

When switching to the next release, we eventually need to refactor `mtd-cal-data = <&art 0x1000>;` to use `nvmem-cells` as well.

2023-05-04 20:49 UTC, merged